// app/layout.tsx
import type { Metadata } from 'next';
import './globals.css'; // グローバルCSSを読み込む場合

export const metadata: Metadata = {
  title: 'My App',
  description: 'Generated by Next.js',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang='ja'>
      <body>
        {/* 背景（seedを固定するとリロードしても同じ配置） */}
        {children}
      </body>
    </html>
  );
}